# 1️⃣ What NumPy actually is (not marketing fluff)
NumPy = fast, memory-efficient, vectorized numerical computation in Python.

In [1]:
# Installation
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 28.3 MB/s  0:00:00m0:00:010:01
Note: you may need to restart the kernel to use updated packages.


In [3]:
# If you write loops on large data instead of NumPy operations → you are doing it wrong and slow.

import numpy as np  # import

# 2️⃣ Creating arrays (the only data structure that matters here)

In [5]:
a = np.array([1, 2, 3])
b = np.array([[1,2,3],[4,5,6]])
print(a,b)

[1 2 3] [[1 2 3]
 [4 5 6]]


In [7]:
# Built-ins you must know:
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye(3))          # identity matrix
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.random.rand(3,3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.45117105 0.62067652 0.78810468]
 [0.38791736 0.1732142  0.51458455]
 [0.60334313 0.11618319 0.64497055]]


# 3️⃣ Shape, type, memory (fundamentals people skip)

In [8]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3,)
1
3
int64


In [9]:
# Changing shape:
print(a.reshape(3,1))
print(a.flatten())
print(a.T)   # transpose

[[1]
 [2]
 [3]]
[1 2 3]
[1 2 3]


# 4️⃣ Indexing & slicing (where most bugs come from)

In [14]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])
print(a[1:4])
print(b[:,1])
print(b[0,2])

1
[2 3]
[2 5 8]
3


In [16]:
# Boolean indexing (critical):
print(b[b > 5])

[6 7 8 9]


In [20]:
# Fancy indexing:
print(b[[0,2,1]])

[[1 2 3]
 [7 8 9]
 [4 5 6]]


# 5️⃣ Vectorized operations (why NumPy exists)

In [23]:
# This replaces thousands of Python loop operations.
print(a + b)
print(a * b)
print(a // b)  // print(a/b)
print(a ** 2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[1 1 1]
 [0 0 0]
 [0 0 0]]
[1 4 9]


In [26]:
# Comparison:
print(a > 5)
print(b > 5)
print((a > 5).sum())
print((b > 5).sum())

[False False False]
[[False False False]
 [False False  True]
 [ True  True  True]]
0
4


# 6️⃣ Math & stats you must know

In [27]:
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.sqrt(a))
print(np.log(a))

6
2.0
1
3
0.816496580927726
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [29]:
# Axis matters:
print(np.sum(b, axis=0))  # column-wise
print(np.sum(b, axis=1))   # row-wise
# If you don’t understand axis, you don’t understand NumPy.

[12 15 18]
[ 6 15 24]


# 7️⃣ Broadcasting (this is where you level up)

In [30]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])

print(a + b)   # b stretches automatically

# If broadcasting confuses you → stop everything and learn it.
# It is non-negotiable.

[[11 22 33]
 [14 25 36]]
